version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/services/app/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /var/www/app
    expose:
      - "9000"
    networks:
      - rede
  nginx:
    build:
      context: .
      dockerfile: ./docker/services/nginx/Dockerfile
    ports:
      - "${NGX_HTTP_PORT}:80"
      - "${NGX_HTTPS_PORT}:443"
    volumes:
      - type: bind
        source: ./app
        target: /var/www/app
      - type: bind
        source: ./docker/data/nginx
        target: /var/log/nginx
    depends_on:
      - app
    networks:
      - rede
  mysql:
    build:
      context: .
      dockerfile: ./docker/services/mysql/Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./docker/data/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "${DB_PORT}:3306"
    networks:
      - rede

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - "${PHP_ADMIN_PORT}:80"
  #   environment:
  #     PMA_ARBITRARY: 1
  #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_USER: '${DB_USERNAME}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'
  #     PMA_HOSTS: mysql
  #   networks:
  #     - rede

networks:
    rede: 
        driver: bridge